#!/usr/bin/env python
import logging
import sys
from datalad.support.annexrepo import AnnexRepo


class Retrieve:

    def __init__(self):
        self.annexrepo = AnnexRepo

    def _getuuid(self):
        """retrieves remote uuid location that is calculated at the initremote"""
        return self.uuid

    def setpresentkey(self):
        pass

    def add_url(self, url):
        self.annexrepo.add_urls(url)

    def get_file(self, file_path):
        self.annexremote._run_annex_command('get', annex_options=file_path,
                                            backend=None, log_online=True,
                                            log_stderr=False, cwd=None)

    def __call__(self, file_path):
        # setpresentkey
        # add url
        # get file
        pass


def main():
    output = sys.stdout
    sys.stdout = sys.stderr
    master = Retrieve(output)


if __name__ == "__main__":
    main()
